export const FAQ_DEFAULT = [
  { intent: "FAQ_PROCESS", question: "How does this process work?", response: "We purchase homes directly for cash. After your property details are verified, we send a contract, and once signed, we match your property with buyers and move to closing." },
  { intent: "FAQ_PROCESS", question: "How long does it take to close?", response: "Closing typically takes 14–30 days depending on inspections, title, and buyer readiness." },
  { intent: "FAQ_CONTRACT", question: "Do I need an inspection?", response: "We buy as‑is. Inspections are optional and used to confirm details during the due‑diligence period." },
  { intent: "FAQ_GENERAL", question: "Do you buy homes as‑is?", response: "Yes, we purchase properties in their current condition. No repairs or cleaning needed." },
  { intent: "FAQ_PROCESS", question: "How do you determine your offer?", response: "We calculate offers using recent comps, repair estimates, and our MAO formula to ensure a fair, realistic price." },
  { intent: "NEGOTIATION", question: "Your offer is too low", response: "I understand. We aim to be competitive while factoring repairs and market data. Can we review comps together and see where we can meet?" },
  { intent: "NEGOTIATION", question: "I want more for my home", response: "I hear you. Our offer reflects current market and repairs. Let’s walk through the numbers and see if adjustments make sense." },
  { intent: "FAQ_CONTRACT", question: "Do I need to put down earnest money?", response: "No. As the seller, you do not provide earnest money. We handle earnest deposits with title when applicable." },
  { intent: "FAQ_FEES", question: "Do I pay closing costs?", response: "We typically cover standard closing costs, so you won’t pay anything out of pocket." },
  { intent: "FAQ_PROCESS", question: "When will I get paid?", response: "Funds are disbursed at closing — typically same day via wire or cashier’s check." },
  { intent: "FAQ_GENERAL", question: "Do I need to provide access?", response: "We’ll coordinate access with you, a key, or a lockbox so qualified buyers can view the property if needed." },
  { intent: "FAQ_GENERAL", question: "Do I need to fix anything before selling?", response: "No, we buy as‑is. Any repairs are factored into our offer — you don’t need to spend upfront." },
  { intent: "FAQ_TRUST", question: "Are you a wholesaler?", response: "Yes, we operate as compliant investors/wholesalers. We use standard agreements and licensed title companies." },
  { intent: "FAQ_GENERAL", question: "Can you take over my mortgage?", response: "In some cases we can take over payments subject‑to existing financing. We review details case by case." },
  { intent: "FAQ_GENERAL", question: "How do I opt‑out?", response: "Reply STOP at any time to unsubscribe from SMS updates." },
  { intent: "NEGOTIATION", question: "I need to think about it", response: "Absolutely — take the time you need. We can follow up in a few days if that works for you." },
  { intent: "NEGOTIATION", question: "Contact me later", response: "No problem. Tell me a good date and time, and I’ll follow up then." },
  { intent: "NEGOTIATION", question: "I’m not sure this is right for me", response: "Totally fair. I’m happy to answer questions so you can decide what’s best for your situation." },
  { intent: "NEGOTIATION", question: "I’m too busy right now", response: "Understood. We can schedule a quick call or text at a convenient time for you." },
  { intent: "FAQ_GENERAL", question: "Do I need to paint or fix small things?", response: "No — we buy as‑is, including minor issues. No prep needed." },
  { intent: "FAQ_GENERAL", question: "What about big repairs?", response: "We account for major repairs in our offer, so you won’t have to fix them first." },
  { intent: "FAQ_PROCESS", question: "Do I get multiple offers?", response: "Yes. We broadcast to vetted buyers and help you evaluate the strongest offers." },
  { intent: "FAQ_PROCESS", question: "How do I know which offer is best?", response: "We compare offers by price, terms, and buyer reliability to help you choose confidently." },
  { intent: "FAQ_FEES", question: "What is an assignment fee?", response: "It’s the fee paid to the wholesaler for securing the contract and finding a buyer." },
  { intent: "FAQ_CONTRACT", question: "How long is your offer valid?", response: "Offers are typically valid 48–72 hours to give you time to review and decide." },
  { intent: "FAQ_PROCESS", question: "I need to sell fast", response: "We specialize in quick closings and can often close in 14–21 days." },
  { intent: "FAQ_PROCESS", question: "Can I wait longer?", response: "Yes, we can accommodate your timeline. Just note the market can shift, affecting price." },
  { intent: "FAQ_PROCESS", question: "How do you calculate market value?", response: "We use recent comparable sales near your property along with current demand and condition." },
  { intent: "FAQ_PROCESS", question: "Do you subtract repair costs?", response: "Yes. Repair estimates are built into the offer so the number is realistic." },
  { intent: "FAQ_GENERAL", question: "How will you contact me?", response: "We use SMS and phone, aligned to your preferences." },
  { intent: "FAQ_TRUST", question: "Is my info confidential?", response: "Yes. Your information is kept confidential and only used for evaluating the property and closing." },
  { intent: "FAQ_FEES", question: "Are there any hidden fees?", response: "No hidden fees. Our process is transparent, and you won’t pay out‑of‑pocket." },
  { intent: "FAQ_GENERAL", question: "I’m moving out of state", response: "We can work remotely and handle documents online with the title company." },
  { intent: "FAQ_PROCESS", question: "Can we close same‑day?", response: "Rarely; proper processing is needed. 1–2 weeks is typical, though we expedite when possible." },
  { intent: "FAQ_GENERAL", question: "Do I need a real estate agent?", response: "No agent is required — we handle the purchase directly." },
  { intent: "FAQ_GENERAL", question: "I have a bankruptcy, can I sell?", response: "Yes. We review the specifics but bankruptcy doesn’t necessarily prevent closing." },
  { intent: "FAQ_GENERAL", question: "I have multiple properties", response: "We can evaluate each and even structure portfolio deals." },
]
