ALTER TABLE lead_sequences
  ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fail_streak INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS disabled BOOLEAN DEFAULT FALSE;
